### ISSUE TITLE
Chrome Extension Revamp

### ISSUE THREAD

**Issue by owocki** [gitcoinco/chrome_ext#2]
1. Explorer should show issues I'm watching, not just all issues
2. Anytime I look at an issues board, it should display the funding of each issue.
3. The notifications are kind of obnoxious.  Don't show notifications for all issues associated with repo.
4. The 'Fund Issue' button is broken right now / doesnt show up on issues.  Fix it.
5. rounding is off http://bits.owocki.com/1m3r3Q0O2E38/Screen%20Shot%202017-10-19%20at%202.28.10%20PM.png
6. ability to just post a funded issue straight away in the extension (without going to the site)

**Comment by jclancy93** [comment]
Hey @owocki, I'm working on the chrome extension bounty. 

Just FYI, I'm not noticing the 5th issue (the bad rounding) what should i do to replicate?

#1 is a little tricky because to get all issues a user is watching, we need to be authenticated on the GH API. This should probably be happening on a backend somewhere, cause I don't see a secure way to get the auth scope we need on client side only

**Comment by owocki** [comment]
i already fixed #5 :)

**Comment by owocki** [comment]
probably best to work off of https://github.com/gitcoinco/web/issues/50 since that's where the funding was posted. ill close this issue now.

**Comment by owocki** [comment]
post is live https://medium.com/gitcoin/gitcoin-chrome-extension-enters-alpha-63f9bdf492e4

**Comment by ethikz** [comment]
@jclancy93 @owocki Nice job!!
